version: "3.9"

services:
  switch:
    build: ./netubuntu
    command: /bin/bash -c "
      ip r r default via 10.0.1.1 &&
      ip r a 10.0.5.8/29 via 10.0.5.3 &&
      iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
      iptables -t nat -A PREROUTING -i eth1 -p udp --dport 1194 -j DNAT --to-destination 10.0.5.11 &&
      iptables -t nat -A POSTROUTING -o eth0 -p udp --dport 1194 -d 10.0.5.11 -j SNAT --to-source 10.0.5.2 &&
      /bin/bash"
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      dmz1_net:
        ipv4_address: 10.0.5.2
      outside_net:
        ipv4_address: 10.0.1.254
    depends_on:
      - snort_ips

  snort_ips:
    image: linton/docker-snort
    command: /bin/bash -c "ip r r default via 10.0.5.2 && snort -q -l /var/log/snort -i eth1 -A console -c /etc/snort/etc/snort.conf -k none"
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./snort_ips/local.rules:/etc/snort/rules/local.rules
      - ./snort_ips/logs:/var/log/snort
    networks:
      dmz1_net:
        ipv4_address: 10.0.5.3
      dmz2_net:
        ipv4_address: 10.0.5.10

  router:
    build: ./netubuntu
    command: /bin/bash -c "

      ip r r default via 10.0.5.10 &&

      iptables -t mangle -A PREROUTING -i eth0 ! -d 10.0.5.11 -j DROP &&
      iptables -P FORWARD DROP &&
      iptables -A FORWARD -i eth1 -o eth0 -m state --state NEW -j ACCEPT &&
      iptables -A FORWARD -i eth2 -o eth0 -m state --state NEW -j ACCEPT &&
      iptables -A FORWARD -i eth3 -o eth0 -m state --state NEW -j ACCEPT &&
      iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT &&
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      
      ip r a 10.0.4.0/24 via 10.0.5.19 &&
      iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 3389 -j DNAT --to-destination 10.0.4.100 &&
      iptables -A FORWARD -i eth0 -o eth3 -p tcp --syn --dport 3389 -m state --state NEW -j ACCEPT &&
      iptables -t nat -A POSTROUTING -o eth3 -p tcp --dport 3389 -d 10.0.4.100 -j SNAT --to-source 10.0.5.18 &&

      iptables -t nat -A PREROUTING -i eth0 -p udp --dport 1194 -j DNAT --to-destination 10.0.3.101 &&
      iptables -A FORWARD -i eth0 -o eth2 -p udp --dport 1194 -m state --state NEW -j ACCEPT &&
      iptables -t nat -A POSTROUTING -o eth2 -p udp --dport 1194 -d 10.0.3.101 -j SNAT --to-source 10.0.3.254 &&

      /bin/bash"
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      dmz2_net:
        ipv4_address: 10.0.5.11
      school_net:
        ipv4_address: 10.0.2.254
      server_net:
        ipv4_address: 10.0.3.254
      snort_net:
        ipv4_address: 10.0.5.18
    depends_on:
      - snort_ips
      
  server:
    build: ./xrdp
    entrypoint: []
    command: /bin/bash -c "ip r r default via 10.0.3.254 && /usr/bin/run.sh admin admin yes"
    cap_add:
      - NET_ADMIN
    networks:
      server_net:
        ipv4_address: 10.0.3.100
    depends_on:
      - router
  
  client:
    build: ./netubuntu
    command: /bin/bash -c "ip r r default via 10.0.2.254 && /bin/bash"
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      - school_net
    depends_on:
      - router
  
  attacker:
    build: ./xrdp
    entrypoint: []
    command: /bin/bash -c "
      echo 'root:root' | chpasswd &&
      echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
      service ssh start &&
      mkdir -p /dev/net &&
      mknod /dev/net/tun c 10 200 &&
      chmod 600 /dev/net/tun &&
      ip r a 10.0.5.8/29 via 10.0.1.254 &&
      /usr/bin/run.sh admin admin yes"
    volumes:
      - ./vpn/client.ovpn:/client.ovpn
      - ./ransomware:/ransomware
    ports:
      - 3389:3389
    cap_add:
      - NET_ADMIN
    networks:
      - outside_net
    depends_on:
      - switch

  vpn_server:
    image: kylemanna/openvpn
    command: /bin/bash -c "ip r r default via 10.0.3.254 && ovpn_run"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./vpn/config:/etc/openvpn
    networks:
      server_net:
        ipv4_address: 10.0.3.101
    depends_on:
      - router

  snort_ids:
    image: linton/docker-snort
    command: /bin/bash -c "ip r r default via 10.0.5.18 && snort -q -l /var/log/snort -i eth1 -A console -c /etc/snort/etc/snort.conf -k none"
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./snort_ids/local.rules:/etc/snort/rules/local.rules
      - ./snort_ids/logs:/var/log/snort
    networks:
      snort_net:
        ipv4_address: 10.0.5.19
      honeypot_net:
        ipv4_address: 10.0.4.254
    depends_on:
      - router

  honeypot:
    build: ./xrdp
    entrypoint: []
    command: /bin/bash -c "ip r r default via 10.0.4.254 && /usr/bin/run.sh admin admin yes"
    cap_add:
      - NET_ADMIN
    networks:
      honeypot_net:
        ipv4_address: 10.0.4.100
    depends_on:
      - snort_ids
    
networks:
  outside_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
  dmz1_net:
    ipam:
      config:
        - subnet: 10.0.5.0/29
          gateway: 10.0.5.1
  dmz2_net:
    name: network_A
    ipam:
      config:
        - subnet: 10.0.5.8/29
          gateway: 10.0.5.9
  school_net:
    name: network_B
    ipam:
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.1
  server_net:
    name: network_C
    ipam:
      config:
        - subnet: 10.0.3.0/24
          gateway: 10.0.3.1
  snort_net:
    name: network_D
    ipam:
      config:
        - subnet: 10.0.5.16/29
          gateway: 10.0.5.17
  honeypot_net:
    ipam:
      config:
        - subnet: 10.0.4.0/24
          gateway: 10.0.4.1